services:
  log-viewer-client-app:
    container_name: viewer-app
    build: ./client
    image: log-viewer-client-app:v1
    ports:
      - 80:80
    expose:
      - 80
    networks:
      - internalnet

  log-viewer-server-app:
    container_name: server-app
    build: ./server
    image: log-viewer-server-app:v1
    restart: always
    ports:
      - 3000:3000
    expose:
      - 3000
    networks:
      - internalnet

networks:
  internalnet:
    driver: bridge